<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DataDonkTM</AssemblyName>
    <RootNamespace>DataDonkTM</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>0.1.0</Version>
    <Product>DataDonk Table Manager</Product>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DataDonkTM.Tests" />
    <EmbeddedResource Include="app.ico" LogicalName="DataDonkTM.app.ico" />
  </ItemGroup>

</Project>
